create table if not exists batch_credit_request_log
(
    credit_request_id           bigint               null,
    clientkey                   bigint               null,
    debtorkey                   bigint               null,
    requested_amount            double               null,
    log_timestamp               timestamp            null,
    manual_review               int                  null,
    request_type                text                 null,
    recent_high_credit          double               null,
    intelliscore                int                  null,
    client_buffer               double               null,
    client_ar_balance           double               null,
    client_blanket_credit_limit double               null,
    recent_unpaid_invoices      int                  null,
    recent_bad_chargebacks      int                  null,
    debtor_ar_balance           double               null,
    having_overdue_balance      int                  null,
    recent_decrease_in_limit    int                  null,
    euler_coverage              double               null,
    prior_partial_decline       int                  null,
    dso_slowdown                int                  null,
    watch_workout_flag          int                  null,
    new_debtor                  int                  null,
    experian_bin                text                 null,
    country                     text                 null,
    oob_or_bk_flag              int                  null,
    fsr                         int                  null,
    experian_sales              double               null,
    employees                   int                  null,
    sic_code                    text                 null,
    coefficient                 double               null,
    exponent                    double               null,
    ratio                       double               null,
    no_buy                      int                  null,
    number_requests_today       int                  null,
    pass_fs_test                int                  null,
    lsq_revenue_estimate        double               null,
    suggested_max_limit         double               null,
    final_decision              double               null,
    buffer_usage                double               null,
    logic_code                  int                  null,
    foreign_request             int                  null,
    no_credit_information       int                  null,
    high_concentration          int                  null,
    above_auto_approval_limit   int                  null,
    over_euler_coverage         int                  null,
    max_requests_in_a_day       int                  null,
    is_test_record              tinyint(1) default 0 null,
    falcon_request_id           bigint auto_increment
        primary key,
    request_api_name            varchar(255)         null,
    is_active_request           tinyint(1)           null,
    delinquency_score           float                null,
    external_data_source        text                 null,
    duns_number_entity          text                 null,
    IsAssocAddr                 varchar(15)          null,
    duns_transaction_id         text                 null,
    default_score               float                null,
    duns_number                 text                 null,
    sales                       float                null,
    scf_reviewed                tinyint(1)           null
)
  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4  collate = utf8mb4_unicode_ci;

